version: '3.8'
services:
  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: time_travel
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/time_travel
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example
    ports:
      - 8080:8080
    depends_on:
      - mariadb

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  db_data:
